### ISSUE TITLE
Buggy formatting for code examples in .mdx files

### ISSUE THREAD

**Issue by sahuguet** [modelcontextprotocol/docs#35]
The formatting of the `.mdx`  pages is messed up.
Your triple backquotes should be at the very beginning of the line (no indentation). It makes the examples harder to read.

```
<Tabs>
  <Tab title="TypeScript (Server)">
    ```typescript                                                   <===== 
    const server = new Server({
      name: "example-server",
      version: "1.0.0"
```

PS: MCP looks really cool. This is a great addition to the ecosystem.
Thank you for sharing it.

**Comment by jspahrsummers** [comment]
Thank you for the feedback!

This is a fairly subjective stylistic choice, and I think we're happy with the current formatting, so I'll close this out. As a workaround, you may find it easier to read the docs either at https://modelcontextprotocol.io (latest `main`) or by running `mintlify dev` for local testing.
