### ISSUE TITLE
Unclear how to work with remote servers in the Desktop App?

### ISSUE THREAD

**Issue by lonelycode** [modelcontextprotocol/docs#40]
All the samples use a local MCP server managed by the Claude Desktop App, does that mean that for remote servers, the server creator needs to provide a client for the dekstop app to use?

It would be good to have more clarity here as it's not immediately obvious from the available docs.

**Comment by dsp-ant** [comment]
We should be more clear about this. At the moment Claude Desktop, Zed and Cody support local connections via STDIO. While the protocol allows for other transports that allow for remote MCP servers, they are not implemented.

We likely could be a bit more clear about this in the documentation.

**Comment by dsp-ant** [comment]
> Is there an ETA on when remote servers will be supported?

We are working on it. I can't give a timeline. Defining protocols, implementing prototypes and validating assumptions takes a lot of time, and so I am not sure when we are done with it. However, I would assume it's a matter of months, not years.
