### ISSUE TITLE
Is "claude_desktop_config.json" or "config.json" of Claude desktop?

### ISSUE THREAD

**Issue by xiaoliwe** [modelcontextprotocol/docs#41]
Hi guys,
Under the macOS, Should I create a new file called "claude_desktop_config.json" or use the "config.json" file directly? 
<img width="450" alt="Screenshot 2024-11-26 at 06 49 13" src="https://github.com/user-attachments/assets/e9ce295d-47b5-49b1-97fe-644b4045904f">

Assume use the "config.json", I've configured the MCP params as below: 
<img width="432" alt="Screenshot 2024-11-26 at 06 45 27" src="https://github.com/user-attachments/assets/d9cf6a7f-2b0c-492d-b8c2-79a14ce01088">

After opening the Claude desktop app --> inputting the prompts, I Did not get the expected results
<img width="756" alt="Screenshot 2024-11-26 at 06 47 44" src="https://github.com/user-attachments/assets/25b5d2f9-0b82-4b56-9167-95cf6624e9ae">

Where is the configuration error? 

Thanks.

**Comment by dsp-ant** [comment]
Please create `claude_desktop_config.json`. `config.json` is used for other things.

**Comment by xiaoliwe** [comment]
Thanks, It's working. 
Cool~
