### ISSUE TITLE
Unable to find claude_desktop_config.json file

### ISSUE THREAD

**Issue by wishtodaya** [modelcontextprotocol/docs#42]
![image](https://github.com/user-attachments/assets/d6bbea6f-b606-4211-aeb0-14f5fc0e6486)

I'm using the latest version of the Claude Desktop application on a Windows 11 system, but I'm unable to find the claude_desktop_config.json configuration file in the %APPDATA%\Claude directory.
I have carefully searched through this directory and also tried using the Windows search function, but I couldn't locate the file.
Since I can't find this file, I am unable to perform some of the customizations I would like to do.

**Comment by jspahrsummers** [comment]
Feel free to go ahead and create this file. Sorry the docs are a bit unclear on this point right now.
