### ISSUE TITLE
[bug] requests.HTTPError-->httpx.HTTPError

### ISSUE THREAD

**Issue by thinkthinking** [modelcontextprotocol/docs#44]
Here's a bug: it should be "httpx.HTTPError" instead of "requests.HTTPError" in the "Implement tool handlers" section at https://modelcontextprotocol.io/docs/first-server/python#check-current-weather:~:text=Implement%20tool%20handlers%C2%A0%E5%AE%9E%E7%8E%B0%E5%B7%A5%E5%85%B7%E5%A4%84%E7%90%86%E7%A8%8B%E5%BA%8F

**Comment by dsp-ant** [comment]
Thank you for reporting this. I have a PR to fix this.
