### ISSUE TITLE
Question: How to enable the developer mode?

### ISSUE THREAD

**Issue by udiedrichsen** [modelcontextprotocol/docs#58]
In the docs I find this:
From Claude Desktop, go to Claude > Settings…    - Open the "Developer" tab to see your configuration

but I my Mac Claude app (newest version downloaded and installed today) 
I dont have this tab.

**Comment by dsp-ant** [comment]
Note there are two settings dialogs in the Claude App. The one for MCP can be accessed via the menu or via ⌘+,
<img width="220" alt="image" src="https://github.com/user-attachments/assets/b8ff5990-a772-4c4f-8cac-f4099ddf7354">

**Comment by udiedrichsen** [comment]
Cool, that works. Thx!

**Comment by timblaktu** [comment]
FWIW, I struggled with this on Windows desktop app, where it's buried in the "Help" hamburger submenu...
