### ISSUE TITLE
Still unclear about functionality of Resources

### ISSUE THREAD

**Issue by burningion** [modelcontextprotocol/docs#69]
**Is your feature request related to a problem? Please describe.**

I've started from the MCP Python quickstart. I'm trying to implement access for my video editing tool.

When I define resources, I'd expect to be able to see them when querying from the Claude desktop tool.

Instead, I don't seem to be able to interact with my defined resources at all.

Is this hidden behind a flag? Should I be able to interact with my resources via Claude?

**Describe the solution you'd like**

Clarify the role of Resources, with a non trivial example. Show how resources work from within the desktop app.

**Describe alternatives you've considered**

For now I'm assuming everything must be behind my `tools`, so I'm using tools to return things like Video IDs.

**Additional context**

I see my resources in the MCP inspector, but don't seem to be able to do anything with said resources, let alone see them in the Claude app (unlike my tools)

<img width="1384" alt="Screenshot 2024-12-03 at 5 02 22 PM" src="https://github.com/user-attachments/assets/23cbdc68-72b7-46cd-a177-f8e6f9277f19">

**Comment by burningion** [comment]
Just wanted to update my comment here, by poking around I've seen that Resources represent data you can attach to prompts within the Claude app, to be made available to system for exploration

In my case, I've got a video analysis JSON, and using this resource allows me to interactively talk with this data:

<img width="997" alt="Screenshot 2024-12-04 at 8 48 03 AM" src="https://github.com/user-attachments/assets/31ad1efd-6ccf-47f4-b148-037119d7cebc">

The way I attach this in the Claude app is via the paperclip icon, which expands out to "Connect to MCP":

<img width="997" alt="Screenshot 2024-12-04 at 8 48 14 AM" src="https://github.com/user-attachments/assets/32876a3c-88e1-4634-9dbd-359defd8e6e0">

From there, I can see all my Resources. 

What would be interesting (to me) would be a way to search resources, as this menu seems less discoverable relative to tool use, and can quickly become overwhelming.

<img width="997" alt="Screenshot 2024-12-04 at 8 48 33 AM" src="https://github.com/user-attachments/assets/da2c865b-d27c-417f-9596-2a7a1480049c">

**Comment by jspahrsummers** [comment]
Going to close this, as this relates specifically to Claude Desktop, and not MCP generally.
