### ISSUE TITLE
Windows instructions are wrong over the file path

### ISSUE THREAD

**Issue by MBlagui** [modelcontextprotocol/docs#81]
Doc says

Over the Windows file format example this is looks invalid json :

{
    "mcpServers": {
        "weather": {
            "command": "uv",
            "args": [
                "--directory",
                "C:\\ABSOLUTE\PATH\TO\PARENT\FOLDER\weather",
                "run",
                "weather"
            ]
        }
    }
}

As all the paths should be \\ ==> C:\\ABSOLUTE\\PATH\\TO\\PARENT\\FOLDER\\weather

**Comment by jspahrsummers** [comment]
Thanks, good catch!
